### ISSUE TITLE
"Did not find a pokemon within the SnipingScanOffset"

### ISSUE THREAD

**Issue by tintin250** [5andr0/PogoLocationFeeder#297]
My entire config looks like this
https://i.gyazo.com/1ca3a5cf28fdaa66d47fb6f80970d11b.png

 Is there anything I can do to fix this or is this the norm now?

**Comment by BobbyWibowo** [comment]
The Pokemon was simple not there. Mostly caused by fake coordinates.

**Comment by ElectroZoom** [comment]
@BobbyWibowo: Yes and no. There are sometimes fake coordinates, that's right but it's never over 50% of all coordinates. If EVERY snipe doesnt find any pokemon it's because you're sniping to fast. You can easiely check it yourself by sniping manually on another account (which isn't in use by a bot or by yourself)

I have the same problem since the "delaybetweensnipes" is ignored and I have no idea why...
