### ISSUE TITLE
config.json is overwritten on every execution!

### ISSUE THREAD

**Issue by y2krazy** [5andr0/PogoLocationFeeder#62]
Upon every run of PogoLocationFeeder.exe, the config.json file is overwritten/cleared.

**Comment by y2krazy** [comment]
Hmm. A connection was established, but it's either going VERY slow, having connection issues, or both. It does not look like we need to modify the config.json any longer?

**Comment by NexLegend** [comment]
Yeah, now it just auto connects to the discord_channels.json channels. HOWEVER, editing these and removing some, doesn't change anything, and the sniper still reads them, even if you deleted them.

And refuses to read any new entries. Dunno if broken.

**Comment by Ilses** [comment]
The config.json is first read, then re-saved. This allows us to push new config settings to existing config.json files. Discord servers are likely going to be a bit slow for a bit.

Discord has assigned us a dedicated feed to use, and the discord_channels.json file cannot be edited. (It probably shouldn't be included in the project). Will update the wiki soon.

**Comment by cl3537git** [comment]
Ilses, great tool but it sounds like in newer versions we won't be able to include our own channels?

**Comment by Ilses** [comment]
Closing this since it seems like you'll want the 0.1.2 version which fixes a lot of the speed issues in v0.1.1 . The `config.json` setup has been updated on the wiki.

@cl3537git Yeah -- sorry about that, but per-user channel inclusion has to be disabled, since we got contacted by Discord's CTO. In the short-term we'll work out a solution to let you ignore channels, and you can PM us with any channels you want added to the feed. Hopefully we can also figure out a good long-term solution to this (probably a single scraping bot and dedicated server).
