### ISSUE TITLE
discord_channels.json doesn't allow proper editing. Also why?

### ISSUE THREAD

**Issue by NexLegend** [5andr0/PogoLocationFeeder#65]
Idk if i like this new discord connection system. It just auto connects to the discord_channels.json channels. HOWEVER, editing these and removing some, doesn't change anything, and the sniper still reads them, even if you deleted them.

And refuses to read any new entries. Dunno if broken."

Also, not sure why we can't use our own credentials to log into a discord. I feel like the connection on the PoGo LoCo is really F'd up and throttled like 75% of the time.

**Comment by Zubinexu** [comment]
Same issues

**Comment by skupfer** [comment]
That's because the used server may not have access to these channels you want to use.

Would be easier with an option to toggle their server or your own user.

**Comment by Ilses** [comment]
We had to switch systems because we were contact by Discord's CTO about traffic issues. The latest 0.1.4 release allows you to ignore channels by removing them from your discord_channels.json, and it should be able to handle connection issues more robustly.

For now, if you'd like a server added to the feed, please ping myself or 5andr0 (or open a [Server Request] issue. Thanks!
