### ISSUE TITLE
Filtering of sources feature removed?

### ISSUE THREAD

**Issue by RichardZhaoE** [5andr0/PogoLocationFeeder#83]
You can no longer choose which server to get your information from. It now feels like I'm sniping pokemon i don't even want to snipe and getting spammed with random coords.

**Comment by am3yar0ra** [comment]
Who said you can't ? You need the server name and the ID to get that working. Maybe the web application would help you get ID and server name.

**Comment by 750z** [comment]
I edited the discord_channel .json file to the channels i want to get. I only added 90+ iv channels etc, and im sniping pokemon with like 20iv snorlaxes... lol

**Comment by siimveskilt** [comment]
People post fakes at these channels all the time.

**Comment by theloser** [comment]
If I understand corrctly: because the Feeder now receives its messages from http://pogo-feed.mmoex.com/messages (see #86), the feeder totally ignores my discord_channel.json, right? After I deleted unwanted channels from discord_channel.json I still get messages from those channels but with "UNKNOWN_SOURCE" (yeah, because the feeder can't get the server and channel name for an id).

I don't mind getting messages from a centralized server, but it should also be possible to "filter" those messages to get only those messages belonging to the channels in my discord_channel.json file.

**Comment by isolah123** [comment]
how about set "true" to UseTransferIvForSnipe, and SnipeIgnoreUnknownIv, thats the filter from necrobots, btw more snipes means more exp

**Comment by theloser** [comment]
Hm. I have both of them set to "false", because many announced coords in channels like "100_iv" don't come with iv values, so my bot would ignore them otherwise, right? I don't care for EXP, I just want a nice stack full of high iv pokemon, therefor I'd prefer to disable channels in which usually only "low level" spottings are posted.

**Comment by Ilses** [comment]
@theloser you are correct -- `discord_channels.json` is only for resolving channel names for the existing feed. We will be working to add server-side options to allow for better filtering of pokemon.

If you would like to add channels to the global feed, please ping myself of 5andr0 and we can take care of it -- the feed system means we no longer require client updates to add or remove channels.

(We are also looking into solutions for fixing badly-formatted entries -- keep your eyes peeled for future releases!)

**Comment by Ilses** [comment]
An ignore channel feature is slated for our next [release](https://github.com/5andr0/PogoLocationFeeder/releases)! You can try it early by building the master branch ;)

**Comment by theloser** [comment]
Great news. Will test it for sure!
