### ISSUE TITLE
Error 503 

### ISSUE THREAD

**Issue by AshBringeR** [5andr0/PogoLocationFeeder#85]
![image](https://cloud.githubusercontent.com/assets/3815426/17323000/d99c609a-58a8-11e6-9a6d-cbbd5dea3e9e.png)

**Comment by bunnyx** [comment]
Same here

**Comment by sabinad256** [comment]
Same here
![screenshot_3](https://cloud.githubusercontent.com/assets/6133308/17323501/229d66c2-58c2-11e6-8d63-9d0e7f3635cd.png)

**Comment by djbie** [comment]
compile new from master

**Comment by akbarz** [comment]
compiled version please, vs cant installed on my pc

**Comment by zzzoperzzz** [comment]
the same

**Comment by Marsinator** [comment]
happens even with pokesnipers to false

**Comment by Ilses** [comment]
Hey everyone -- integration with PokeSnipers was broken by addition of CloudFlare DDoS protection. There was a bug where PokeSnipers was being checked even when toggled off, but that should be fixed in the current release.

The broken PokeSnipers.com integration is a known bug, and should be fixed at a later date.
